### ISSUE TITLE
Drop ENV=X url param and just use the wallet eth network

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/unity-renderer#288]
Right now, we have ENV=org url param to set the org environment, and this environment doesn't work in ropsten. Likewise, we have ENV=zone for ropsten, and doesn't work for mainnet.

We have even implemented error screens for this! We should just detect the target network and map ropsten to zone and mainnet to org, it's way more user-dev-dog-friendly.

**Comment by olavra** [comment]
maybe change the paramter to NET=ropsten | mainnet

**Comment by olavra** [comment]
se ha sugerido que sin parametro sea automatico, agarrando la network que este seteada en la wallet

**Comment by olavra** [comment]
algunos sistemas tienen hardcodeado el ORG, por lo que deberia tener retrocompatiblidad

**Comment by olavra** [comment]
tenemos que considerar que hay usuarios que no usan wallet, por lo que debemos seguir siendo capaces de forzar la red en cada entorno

**Comment by menduz** [comment]
Fixed in https://github.com/decentraland/explorer-technical-backlog/issues/23

**Comment by BrianAmadori** [comment]
Reopening this issue because the issue persists. If I'm on the wrong network and don't set any flag, we still have a blocker error screen.

**Comment by BrianAmadori** [comment]
cc: @menduz

**Comment by menduz** [comment]
That is expected, to prevent human errors :( being too permissive caused involuntary confusion. So if you need to use ropsten, it needs to be explicit. Do you think we can find a way around it?
